global using System;
global using System.Collections.Generic;
global using System.Globalization;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using MediatR;
global using TimeTracker.Common;
global using TimeTracker.Contract.Converters;
global using TimeTracker.Contract.Dtos;
